### ISSUE TITLE
[RFC] Admin marketplace

### ISSUE THREAD

**Issue by leomp12** [ecomclub/admin-marketplace#1]
### Setup

- [ ] Setup project with Vue CLI 4;
- [ ] Use Vuex and Vue Router (suggestion);
- [ ] Use [Bootstrap](https://getbootstrap.com/) and [Bootstrap Vue](https://bootstrap-vue.js.org/) (Bootstrap CSS must be out of SPA bundle);

### What

This app should be a part of [ecomplus-admin](https://github.com/ecomclub/ecomplus-admin) (microfrontend, not so micro :stuck_out_tongue:), on some admin route it'll be loaded (JS only with Webpack dynamic import), then it'll also load nested routes (Vue Router) bundles dynamically (some of them).

> As a reference, [storefront-app](https://github.com/ecomclub/storefront-app) has the same approach (but for [storefront-template](https://github.com/ecomclub/storefront-template)).

- [ ] `/#/apps` Default route must list all apps from public E-Com Plus Market API (https://github.com/ecomclub/market/issues/11), and installed apps (highlighted), listed from [Store API /applications](https://developers.e-com.plus/docs/api/#/store/applications/);
- [ ] `/#/apps/:category` List apps from public E-Com Plus Market API with `category` filter;
- [ ] `/#/apps/edit/:slug` And the last view is to install/configure respective app (by slug):
  - Install app if not installed;
  - If app installed:
    1. _gambiarra_: (edit) fixed routes (specifying `slug` param value) to load (**dynamic import**) specific forms by app slug, for `correios` we'll have a defined form, for `paghiper` we'll have another...
    2. When switch doesn't match any preseted cases we must render `admin-settings` (if present) field to form using some JSON Schema to form parser.
    3. On form submit send PATCH to Store API to save application `data`/`hidden_data`;

## RFC

To GET and PATCH installed applications and from Store API we need _My-ID_ and _Access-Token_, of course we already have those credentials on admin (from login), but they're not set globally for security reasons (and I don't like this idea), ideas to solve it?

Remember that `admin-marketplace` is an SPA, not a component (can't be because of dynamic imports).

I'm thinking about using `localStorage` temporarily to pass them, on startup  `admin-marketplace` would read those `localStorage.getItem` and then clear.

**Comment by talissonf** [comment]
I think for the persistence of login data, we can create a lib to handle login and save it to sessionStorage instead of localStorage. This lib could also be used on the market site and not just admin.

**Comment by leomp12** [comment]
@talissonf the best solution, just a little bit more laborious.
But lets do that, I'll create a new repo!

**Comment by leomp12** [comment]
Edit.: I was suggesting using switch statement to load specific app forms dynamically, but I think we can do that directly from router specifying `slug` param value, example routes object with suggested implementation:

```js
const routes = [
  {
    path: '/',
    redirect: '/apps'
  },
  {
    path: '/apps/:category?',
    name: 'applications',
    component: Applications
  },
  {
    path: '/apps/edit/correios',
    name: 'correios',
    component: () => import('../views/Applications/Correios.vue')
  },
  {
    path: '/apps/edit/paypal',
    name: 'paypal',
    component: () => import('../views/Applications/PayPal.vue')
  },
  {
    path: '/apps/edit/:slug?',
    name: 'application',
    component: Application
  }
]
```

wdyt @thiagoabreudev ?

**Comment by leomp12** [comment]
### Updating

[`@ecomplus/i18n`](https://github.com/ecomclub/i18n) was released, we must update the app to handle internationalization with this lib :+1: 

And I'm waiting your opinion [here](https://github.com/ecomclub/ecomplus-admin/issues/60), depending of decision we should start using Ant Design here too

**Comment by talissonf** [comment]
Still missing words on [`@ecomplus/i18n`](https://github.com/ecomclub/i18n) for admin-market vocabulary, we can help?

**Comment by leomp12** [comment]
@talissonf sure!
