### ISSUE TITLE
[RFC] Alterar views atuais para Ant Pro

### ISSUE THREAD

**Issue by thiagoabreudev** [ecomclub/admin-marketplace#14]
Temos algumas views implementadas que precisam ser alteradas para usar o [Ant Design Vue Pro](https://preview.pro.loacg.com/). Gostaria de abrir uma discussão para que possamos apontar as views mais adequada pra cada view que temos hoje. Segue print de views

![image](https://user-images.githubusercontent.com/4981847/69191409-2f9e5580-0b01-11ea-8799-e8e38f4ebc0a.png)

![68697106-f3954e80-055c-11ea-8447-19d0b0d96ca3](https://user-images.githubusercontent.com/4981847/69192064-9a9c5c00-0b02-11ea-8c3b-aed87422660e.gif)

**Comment by matheusgnreis** [comment]
Acredito que a view de mostrar os aplicativos poderiam ser [essa](https://preview.pro.loacg.com/list/search/project)
 
![viws-apps](https://user-images.githubusercontent.com/35343551/69197292-bb1ee300-0b0f-11ea-8c1e-b1d8ec704c7e.png)

Com o input que é um filtro por tag e outro por categoria por exemplo.

**Comment by leomp12** [comment]
@matheusgnreis acho que você poderia abrir dois issues separados (um pra cada view) e descrever isto melhor?
Seria bacana prints mais descritivos, acho que você pode inspecionar elemento no navegador, remover alguns elementos que não forem utilizados e alterar alguns textos (escrever algumas categorias por exemplo no lugar onde ficariam as categorias), e depois printar, pode ser?

**Comment by talissonf** [comment]
@matheusgnreis usa o desing mood do chrome pra alterar o conteúdo da página sem precisa inspecionar o elemento. Talvez seja mais intuitivo pra você. 
https://dev.to/arbaoui_mehdi/edit-your-website-live-in-google-chrome-by-using-document-designmode-5d9h
