### ISSUE TITLE
[View] Lista de aplicativos

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/admin-marketplace#17]
Segue um modelo que acredito ser bacana conforme o Ant Design Pro, onde há apenas um filtro de categorias via seleção (OR).

Teremos uma aba que existe todos os aplicativos e outra apenas os instalados pela loja. Abaixo segue o print da aba dos aplicativos a serem visuaizados, onde no card existe a imagem que representa o app, nome do app e uma pequena descrição do mesmo. Logo abaixo um contador de curtidas do app, se acharem necessário, mas acredito que seja legal devido ao cliente procurar instalar aquele que foi mais utilizado.

Isso é apenas uma demonstração obviamente, se puderem dar opiniões sobre.

![view-app](https://user-images.githubusercontent.com/35343551/69263539-434ec800-0ba4-11ea-9be5-606d8eb95c36.png)
![view-app1](https://user-images.githubusercontent.com/35343551/69263541-45188b80-0ba4-11ea-9a5c-bcd79327cc88.png)

Agora sobre a aba de meus aplicativos, pensei em algo como:
 
![my-app](https://user-images.githubusercontent.com/35343551/69268782-8d3cab80-0bae-11ea-9150-2f2285524221.png)

Onde mostra apenas um ícone e nome do aplicativo, seguido da versão do mesmo, junto com o seu respectivo status, pois o mesmo pode estar instalado, mas desativado, logo não funcionará ou instalado e ativo para uso.

No card actions coloquei um ícone de edição juntamente com uma tooltip para facilitar o entendimento pelo lojista, assim como um icone de deletar e outro de compartilhar aplicativo. Se por ventura achar que deva ter mais icone, por padrão ele tem 4, retirei.

**Comment by matheusgnreis** [comment]
@thiagoabreudev @talissonf @leomp12 se puderem opinar posteriormente, agradeço

**Comment by matheusgnreis** [comment]
Atualizando

![my-app1](https://user-images.githubusercontent.com/35343551/69271359-72206a80-0bb3-11ea-8c78-0a558f9c632c.png)

**Comment by leomp12** [comment]
Desassinei todo mundo pra não confundir.
Favor assinar o issue quem for trabalhar nesta implementação :grimacing:

**Comment by matheusgnreis** [comment]
![lista-de-apps](https://user-images.githubusercontent.com/35343551/69368319-aca00b00-0c78-11ea-845d-86d60f8b275d.png)
