### ISSUE TITLE
[View] Página de aplicativo

### ISSUE THREAD

**Issue by leomp12** [ecomclub/admin-marketplace#18]
Substituindo https://github.com/ecomclub/admin-marketplace/issues/14 (em conjunto de https://github.com/ecomclub/admin-marketplace/issues/17)
@matheusgnreis pode me ajudar aqui?

**Comment by matheusgnreis** [comment]
![meu-app](https://user-images.githubusercontent.com/35343551/69368360-c2adcb80-0c78-11ea-91ed-31bdd51c2fdd.png)

**Comment by talissonf** [comment]
Eu tinha pensando nessa dessa forma tambem @matheusgnreis  HAHAH

![Captura de tela de 2019-11-20 12-51-42](https://user-images.githubusercontent.com/14341511/69369323-a27f0c00-0c7a-11ea-89b2-26b0aaaf6758.png)

**Comment by matheusgnreis** [comment]
Ficou bem parecido mesmo hahaha, mas precisa ter o botão verde para instalar igual o meu, peguei lá em [https://antdv.com/components/button/](https://antdv.com/components/button/) além de uma aba de configuração do aplicativo. Acho que dessa forma fica mais organizado.

**Comment by talissonf** [comment]
Eu também acho que a sua ta bem melhor! HAHHA

**Comment by matheusgnreis** [comment]
De acordo com esse preview que mostrei, fiz o clone do repositorio do loac e fiz essa view pegando os elementos como imagem, descrição e outros via computed por exemplo como fizeram no marketing, então creio que já um modelo pronto ajudaria no trabalho de vocês

[account.zip](https://github.com/ecomclub/admin-marketplace/files/3877827/account.zip)
