### ISSUE TITLE
Dinamic imports Discoverer

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/admin-marketplace#41]
Thiago, preciso que no discoverer.js os imports não sejam dinâmicos, para que eu consiga importa-los no painel da e-com plus para que funcione corretamente os inputs

**Comment by leomp12** [comment]
https://github.com/ecomclub/admin-marketplace/commit/742b31216d21285721c2785a6708017377741dc4
https://github.com/ecomclub/admin-marketplace/commit/e76943808767de2a63859e2c040a2062d8fbf0de
