### ISSUE TITLE
Renderizar date inputs

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/admin-marketplace#72]
Doesnt appear mask input for start and end date

**Comment by leomp12** [comment]
Tratar schema type `string` e format `date-time` para renderizar o inputs de data corretamente.

**Comment by leomp12** [comment]
@vitorrgg

**Comment by leomp12** [comment]
Pronto jovens.
@matheusgnreis pode atualizar para a versão `0.2.10` no dashboard por favor?
Vou fechar este issue :ok_hand:
