### ISSUE TITLE
Input number limite

### ISSUE THREAD

**Issue by talissonf** [ecomclub/admin-marketplace#73]
Os inputs de tipo `number` estão com limite de 99999999, se eu tento utilizar um número maior no input como é o caso do bling que onde o id da loja a ser setado tem mais de oito dígitos ex `203389598` ele deixa o input com o padrão máximo que é 99999999.

**Comment by leomp12** [comment]
@talissonf não tenho certeza se isso é um bug, você poderia salvar este ID do Bling como string, me parece mais adequado considerando um número tão grande.

**Comment by talissonf** [comment]
Pode ser também.
